project_id = "yxssxqjhorctkqqdkhzx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://yxssxqjhorctkqqdkhzx.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MB"

[functions]
enabled = true
port = 54325

[functions.analyze-financial-news]
verify_jwt = false

[functions.daily-summary]
verify_jwt = true

[functions.market-data]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[realtime]
enabled = true
port = 54323
ip_version = "IPv4"

[[realtime.tenant]]
name = "realtime"
database = "postgres"
host = "localhost"
port = 54322
max_connections = 20
[realtime.tenant.database]
user = "supabase_admin"
password = "postgres"

[realtime.tenant.database.extensions]
name = "pg_replication_slot"