// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxssxqjhorctkqqdkhzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4c3N4cWpob3JjdGtxcWRraHp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjQ1NDAsImV4cCI6MjA2OTA0MDU0MH0.mJWr6W9PPHwHopTfe66IyOFh2uOUfd9XergXezIlmjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});